import type {LangCode} from './languages';

export type UiLocale = 'en' | 'zh';

export const UI_COPY = {
  en: {
    landingTaglineTop: 'one conversation.',
    landingTaglineBottom: 'then gone.',
    landingFeatureMatched: 'matched by language',
    landingFeatureNoHistory: 'zero accounts, zero history',
    landingFeatureGone: 'close tab = it never happened',
    landingStart: 'start drifting',
    landingHint: 'somewhere out there, a stranger is waiting.',
    wakingTitle: 'waking up...',
    wakingHint: 'free servers sleep when idle · just a moment',
    languageTitle: 'choose your language',
    continue: 'continue →',
    verifying: 'verifying…',
    humanCheckOff: 'human check is off in this environment.',
    changeHintLead: 'your previous choice was saved.',
    changeHintTail: 'change language below if needed.',
    waitingMessages: [
      'finding your match...',
      'someone out there is waiting too',
      'connecting across timezones...',
      'almost there',
    ],
    waitingEmpty: (langLabel: string) => `no one waiting in ${langLabel} yet`,
    waitingOthers: (count: number) => `${count} other waiting`,
    cancel: 'cancel',
    end: 'end',
    typePlaceholder: 'type something...',
    disconnectedTitle: 'they drifted away.',
    disconnectedSubtitle: 'that conversation is gone forever.',
    driftAgain: 'drift again',
    goHome: 'go home',
    changeLanguage: 'change language',
  },
  zh: {
    landingTaglineTop: '只聊一场。',
    landingTaglineBottom: '然后消失。',
    landingFeatureMatched: '按语言匹配',
    landingFeatureNoHistory: '不用账号，不留历史',
    landingFeatureGone: '关掉页面，就像没发生过',
    landingStart: '开始漂流',
    landingHint: '世界某处，正好也有人在等。',
    wakingTitle: '服务器正在醒来…',
    wakingHint: '免费服务器空闲会休眠 · 稍等一下',
    languageTitle: '选择你的聊天语言',
    continue: '继续 →',
    verifying: '验证中…',
    humanCheckOff: '当前环境还没开启人机验证。',
    changeHintLead: '你上次的语言选择还在。',
    changeHintTail: '如果要改，就在下面切。',
    waitingMessages: [
      '正在找和你对上的人…',
      '也许另一边也有人正在等',
      '跨时区连线中…',
      '快了',
    ],
    waitingEmpty: (langLabel: string) => `${langLabel} 现在还没人排队`,
    waitingOthers: (count: number) => `还有 ${count} 个在等`,
    cancel: '取消',
    end: '结束',
    typePlaceholder: '输入点什么…',
    disconnectedTitle: '对方漂走了。',
    disconnectedSubtitle: '这段对话已经彻底消失。',
    driftAgain: '再漂一次',
    goHome: '回首页',
    changeLanguage: '切换语言',
  },
} as const;

const LANGUAGE_LABELS: Record<UiLocale, Record<LangCode, string>> = {
  en: {
    en: 'English',
    zh: 'Chinese',
    es: 'Spanish',
    fr: 'French',
    ja: 'Japanese',
    ko: 'Korean',
    de: 'German',
    pt: 'Portuguese',
    ru: 'Russian',
    ar: 'Arabic',
    any: 'Any Language',
  },
  zh: {
    en: '英语',
    zh: '中文',
    es: '西班牙语',
    fr: '法语',
    ja: '日语',
    ko: '韩语',
    de: '德语',
    pt: '葡萄牙语',
    ru: '俄语',
    ar: '阿拉伯语',
    any: '任意语言',
  },
};

export function getLanguageLabel(code: LangCode, locale: UiLocale): string {
  return LANGUAGE_LABELS[locale][code] || code;
}
